name: Blog CI/CD

# 触发条件：在 push 到 hexo-blog-backup 分支后触发
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
      - name: Checkout codes
        uses: actions/checkout@main #第一步是获取源码

      - name: Setup node
        # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: 安装hexo-cli 以及依赖包
        # 下载 hexo-cli 脚手架及相关安装包
        run: |
          npm install -g hexo-cli
          npm install

      - name: 生成静态资源
        # 编译 markdown 文件
        run: |
          cd ./blog
          hexo clean
          hexo generate

      - name: 部署博客
        env:
          # Github 仓库
          GITHUB_REPO: github.com/OriginMing/OriginMing.github.io
        # 将编译后的博客文件推送到指定仓库
        run: |
          cd ./public && git init && git add .
          git config user.name "OriginMing"
          git config user.email "2368102002@qq.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.BLOG }}@$GITHUB_REPO" master:master
